[workspace]
members = ["orchestrator", "rust-default", "backend", "sql-abstractor", "load-test", ]

resolver="2"
exclude = ["execution_test",  "student_delivery", "backend/frontend", "procedural-macros"]
